version: '3.8'

services:
  node-app:
    build: .
    image: node-app
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - .:/usr/src/node-app
    networks:
      - node-network

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql

volumes:
  dbdata:
    driver: local

networks:
  node-network:
    driver: bridge
